_wandb:
    value:
        cli_version: 0.23.1
        e:
            7aorq36axgznff9wj5or2oyfflax9gzl:
                args:
                    - data/all naming subjects.xlsx
                    - --patience
                    - "5"
                    - --batch_size
                    - "128"
                    - --data_size
                    - "10_000"
                    - --primecondition
                    - "1"
                    - --epochs
                    - "50"
                    - -c
                    - word_embeddings
                codePath: try_to_train.py
                codePathLocal: try_to_train.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "486011826176"
                        used: "318629953536"
                email: tiyliu@ucdavis.edu
                executable: C:\Users\timoy\OneDrive\Desktop\VindictiveSemanticPriming\.venv\Scripts\python.exe
                host: Timo-works
                memory:
                    total: "16849293312"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\timoy\OneDrive\Desktop\VindictiveSemanticPriming\try_to_train.py
                python: CPython 3.14.2
                root: C:\Users\timoy\OneDrive\Desktop\VindictiveSemanticPriming
                startedAt: "2026-01-12T01:47:35.960035Z"
                writerId: 7aorq36axgznff9wj5or2oyfflax9gzl
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "4": 3.14.2
            "5": 0.23.1
            "6": 4.57.3
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
